version: '3'

services:
  webapp:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/app
      - mlflow_data:/mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow
    command: mlflow server --host 0.0.0.0 --backend-store-uri /mlflow/mlruns

volumes:
  mlflow_data: