channels:
- conda-forge
dependencies:
- python=3.9.21
- pip<=23.0.1
- pip:
  - mlflow==2.8.0
  - cloudpickle==2.2.1
  - numpy==1.24.0
  - packaging==23.2
  - pandas==2.0.0
  - psutil==5.9.8
  - pyyaml==6.0.2
  - scikit-learn==1.2.2
  - scipy==1.13.1
  - xgboost==2.0.0
name: mlflow-env
